### ISSUE TITLE
Bug - Fixed width text expands to auto when symbol instance used

### ISSUE THREAD

**Issue by milk-shake** [DWilliames/paddy-sketch-plugin#101]
### Bug report

Sketch: 49.3 (51167)
Paddy: 1.0.7

I checked some old closed issues which reported this behavior and it appeared to be fixed for those guys, but I'm having this issue.

#### Expected behavior:
The text to be the width set and the padding to be around it, like the symbol on the symbols page

#### Actual behavior:
The gif is super crunched and a bit on the speedy side, but it should be enough to show the issue:
![sketch](https://user-images.githubusercontent.com/19327853/38595631-e22c4ef8-3d87-11e8-82cb-433694ec6740.gif)

#### Steps to reproduce:

Create a new symbol with a background of [20], add in a title and some content (both fixed width) and the symbol will get the correctly applied padding

Make an instance of that symbol on a page and the text gets converted to auto width, which looks a bit daft.

Everything else seems to work absolutely perfectly though.
Thanks for your hard work on this plugin, its a massive time / effort saver!

**Comment by johnthachil** [comment]
**+1** on this. It's really frustrating that the Fixed width text expands to auto when symbol instance used

Thanks for this project, really, it's great!

**Comment by milk-shake** [comment]
@wouterramaker it looks like it is, i'll close this and reference your issue
