### ISSUE TITLE
Right padding glitch when working with Anima stacked groups

### ISSUE THREAD

**Issue by blynkkk** [DWilliames/paddy-sketch-plugin#130]
Thanks for one of the most useful plugins ever made!
We use [Anima Layout](https://medium.com/sketch-app-sources/introducing-auto-layout-for-sketch-24e7b5d068f9) stacked groups a lot. The combination of those 2 plugins is incredibly powerful, but it doesn't work, unfortunately. 

It would be great if you could take a look. Thanks! 🙏

### Steps to reproduce:
1. Make a stacking group with Anima, add background layer
![image](https://user-images.githubusercontent.com/11541426/44280151-e090b300-a221-11e8-9ea6-4e1e2ba1c8ac.png)

![image](https://user-images.githubusercontent.com/11541426/44280378-90feb700-a222-11e8-944b-fde802ef5a91.png)

2. Apply Paddy to background
![image](https://user-images.githubusercontent.com/11541426/44280194-f8683700-a221-11e8-9b9a-f2fb6b9abb49.png)

3. 3 paddings work ok, the right one is always like that
![image](https://user-images.githubusercontent.com/11541426/44280331-6dd40780-a222-11e8-9843-fa1b13ffcf1c.png)

**Comment by blaskotron** [comment]
I think he's commented that the two plugins are not compatible/supported. Paddy has its own stacks feature and I disabled autolayout.
