### ISSUE TITLE
When ignoring vertical padding, Paddy misbehaves

### ISSUE THREAD

**Issue by petrchutny** [DWilliames/paddy-sketch-plugin#132]
This is an issue template.

Please fill in the relevant fields – whether this is a **Feature request** or a **Bug report**
Remove any sections that are not relevant to you.

#### Expected behavior:

I would expect paddy to apply 15px padding from both top and bottom when I give it a rule of [15 x]

#### Actual behavior:
(Please include a screenshot or screen recording if possible)

Paddy keeps applying the 15px padding from top, but bottom padding is suddenly smaller.

#### Steps to reproduce:
(Please attach a Sketch file if poss

ible)

Create a button with text, aligned which has "auto" alignment. Set paddy padding to [15 x]. Resize the container shape of the button and watch the padding change in a wrong way.
Sketch file:
[Tinkamo App Design.zip](https://github.com/DWilliames/paddy-sketch-plugin/files/2313434/Tinkamo.App.Design.zip)
Video:
[Paddy misbehaving Video.zip](https://github.com/DWilliames/paddy-sketch-plugin/files/2313436/Paddy.misbehaving.Video.zip)

**Comment by blaskotron** [comment]
Can you check if this is still an issue? When I open your file and resize the instance it goes back to the proper height.

**Comment by petrchutny** [comment]
Thanks a lot @blaskotron, I've installed the beta of Paddy 2, very happy to discover all the new features, as well as the fact that this is working fine now :) Good times! 👍
