### ISSUE TITLE
Resizes abruptly with Anima's Stack in Symbols

### ISSUE THREAD

**Issue by yapjonathan** [DWilliames/paddy-sketch-plugin#17]
Hey David, as mentioned on Facebook, I'm capturing the issue that I ran into when I was trying to create a modal/dialogue box. 

This happens when I combine a paddy button with anima stack and it basically behaves very abruptly upon interacting with it. 

I've attached a screen capture of the issue here and attaching the sketch file I have setup without paddy. [sketch file and screen recording.zip](https://github.com/DWilliames/paddy-sketch-plugin/files/1716382/sketch.file.and.screen.recording.zip)

I don't know if this is related but sounds like the width may be linked. #12

**Comment by DWilliames** [comment]
Thanks for reaching out @yapjonathan. I'll look into this when I get a chance 👍

**Comment by DWilliames** [comment]
@yapjonathan  I have just released **version 1.0.3** – in this version I don't seem to be able to replicate your issue in your example Sketch file; so I think it has been fixed. I'll close this issue for now. If you find the issue still persists, then please re-open it. 👍
