### ISSUE TITLE
[enhancement] Auto-fill padding from selection

### ISSUE THREAD

**Issue by sldx** [DWilliames/paddy-sketch-plugin#24]
As the title says, it would be pretty nice to not have to measure and enter paddings manually, and instead they should be taken from the current selection. Then you wouldn't necessarily have to show the popup either

**Comment by DWilliames** [comment]
That would be a great idea! 👍 

I think I'd still show the pop-up, just in case you do want to tweak them first.
But if you don't need to tweak it; you'd just simply tap 'Control + Alt + p' then 'Enter'. :)

**Comment by vic-topcoder** [comment]
This is the default behavior of Modulizer (https://github.com/Falkeyn/Modulizer) - when you select an element and it is within a group, the plugin will populate the input with the detected padding values.

**Comment by DWilliames** [comment]
@sldx and @vic-topcoder –  I have just released **version 1.0.3** that should make this work. I've make it a separate option in the Paddy menu – and to my surprise, there doesn't seem to be any keyboard shortcut that uses **`Command + p`** within Sketch; so now **`Command + p`** will set padding, with the implied amount. This leaves the current functionality in tact; for others who are used to entering values each time. But for power users; it is now even easier.

 I'll close this issue for now. If you find the issue still persists, then please re-open it. 👍
