### ISSUE TITLE
[Bug] Layer resize arbitrarily when you try to create a symbol

### ISSUE THREAD

**Issue by danielmariluz** [DWilliames/paddy-sketch-plugin#25]
when you apply a paddy plugin to a group of layers and you want to convert one layer of that group into a symbol, that a layer resize arbitrarily...
![feb-15-2018 19-02-59](https://user-images.githubusercontent.com/2532631/36287507-5c1ba84c-1283-11e8-87af-ed5bea7be4d4.gif)

**Comment by DWilliames** [comment]
Thanks for this @danielmariluz.

I've made some changes in v1.0.3, which I'll release soon. Those changes seem to fix it. See below:
![2018-02-18 17 03 48](https://user-images.githubusercontent.com/6570446/36348897-d63a4aec-14cd-11e8-9f43-73c467409e4a.gif)

**Comment by DWilliames** [comment]
@danielmariluz I have just released **version 1.0.3** which seems to fix this. I'll close this issue for now. If you find the issue still persists, then please re-open it. 👍
