### ISSUE TITLE
[Enhancement] Padding to ignore nested layers

### ISSUE THREAD

**Issue by chriscac** [DWilliames/paddy-sketch-plugin#26]
i wanna be able to use the "-" to ignore a nested layer... right now it paddy doesnt.

<img width="229" alt="screen shot 2018-02-16 at 3 23 45 pm" src="https://user-images.githubusercontent.com/4434179/36293397-6d06cc9a-132d-11e8-85d9-1b68136609ad.png">

**Comment by DWilliames** [comment]
@chriscac  I have just released **version 1.0.3** which should make this work. I'll close this issue for now. If you find the issue still persists, then please re-open it. 👍
