### ISSUE TITLE
[Bug] Padding Breaks When Detaching Overriden Symbol, & When Using Craft Sync Plugin for Invision

### ISSUE THREAD

**Issue by dannylodesigns** [DWilliames/paddy-sketch-plugin#27]
It seems that there is an issue with padding that I've noticed due to my use of [Craft](https://www.invisionapp.com/craft?utm_source=google&utm_medium=paid_search&utm_campaign=AW_EC_G_NAM_Search_SemiBranded_EM&utm_content=Craft_Plugins_EM&utm_term=craft%20plugins_e&_bk=craft%20plugins&_bt=218892243535&_bm=e&_bn=g&gclid=CjwKCAiAn5rUBRA3EiwAUCWb2zp42f3rYrE20nNry45Q6DgDZ6h41iEcSAICwl85Sh7Nxc4kDRBhLhoCNQEQAvD_BwE).

I noticed that whenever I sync and check the inspect tool in Invision, my overriden button symbols looks something like this:
<img width="267" alt="screen shot 2018-02-16 at 10 27 46 am" src="https://user-images.githubusercontent.com/36542393/36315465-d0b403c0-1305-11e8-97c7-ff25de5f4011.png">
This is what the structure looks like for the original symbol:

![screen shot 2018-02-16 at 10 40 53 am](https://user-images.githubusercontent.com/36542393/36315522-f3ebcd8c-1305-11e8-8797-982410e1d2c3.png) ![screen shot 2018-02-16 at 10 50 50 am](https://user-images.githubusercontent.com/36542393/36316075-4be52122-1307-11e8-9b15-17769e10835f.png)

I've noticed that when I sync to Invision the button seems to move and you can briefly see the issue occuring. The symbol has not been detached, just overriden, and is still a symbol after the sync has completed:

![giphy](https://user-images.githubusercontent.com/36542393/36315763-792553a6-1306-11e8-9736-39266735a96d.gif)

In my effort to try and track the issue down, I've noticed that this happens even without trying to use the craft plugin, if I ever detach an overriden button symbol which has paddy applied:

![screen shot 2018-02-16 at 10 34 07 am](https://user-images.githubusercontent.com/36542393/36315845-b47ed616-1306-11e8-9f82-31ef40128617.png)

Not sure if the issue is with how I'm setting up the original symbol with "Auto" Alignment, or if any of the other parameters that are set on the text/button background are incorrect, but I wanted to report what was happening in case that this isn't an issue with my workflow.

Otherwise, love this plugin so far! It's been a crazy time saver for keeping consistency across projects.

Thanks!
-Danny

**Comment by vic-topcoder** [comment]
The same issue appears with Anima App auto layout and Craft - the stacked layers lose their position while the plugin runs, but then are recalculated. I wonder what would cause this behavior.

**Comment by DWilliames** [comment]
Yeah this is really weird. I think this is actually a bug with 'Detach from symbol' within Sketch itself.

I tried a simple button symbol in Sketch, with Paddy ***uninstalled.*** And it still resizes funny after detaching from symbol. View GIF below...
![detach from symbol](https://user-images.githubusercontent.com/6570446/36348822-15d48296-14cc-11e8-87ee-b7cb8b5db43c.gif)

I suggest filing a Bug report with Sketch – https://www.sketchapp.com/support/contact/ 
I have done this; and maybe the more detailed bug reports they can get; the more likely it will get fixed, and be easier for them to fix.

**Comment by dannylodesigns** [comment]
@DWilliames now since 1.0.3 update, overriding a button symbol that is was built with padding [10 20] on the button's background layer, the symbol doesn't respond at all to the overridden text (if it's longer or shorter than original)

**Original Symbol (built with [10 20] on background layer)**
![screen shot 2018-02-21 at 1 18 36 pm](https://user-images.githubusercontent.com/36542393/36497600-c7c4db10-1709-11e8-8aa6-5348b4a9bcb4.png)

**Overriden Symbol Text**
![screen shot 2018-02-21 at 1 18 48 pm](https://user-images.githubusercontent.com/36542393/36497599-c7bb2516-1709-11e8-8a61-ef80eeafe1f6.png)

It will only work and respond to the text change if I go to the symbols page and edit the text in the original grouping.

**Comment by DWilliames** [comment]
That's extremely weird @dannylodesigns – it should definitely still support Symbols.

Can you double check in a sneak peak of the next version if this is working for you: https://github.com/DWilliames/paddy-sketch-plugin/archive/v1.0.4.zip

**Comment by DWilliames** [comment]
I just pushed a release (v1.0.4) that should now fix this. 👍 

I will close this issue for now, assuming that the fix is stable — if you find that it hasn't been fixed, then please re-open this issue.

Cheers!
