### ISSUE TITLE
[BUG] vertical spacing not responsive

### ISSUE THREAD

**Issue by redhajr** [DWilliames/paddy-sketch-plugin#30]
i placed a vertical space between group and it takes time to work. it didn't work directly

**Comment by DWilliames** [comment]
Thanks for reaching out @redhajr.

Are you able to provide a bit more context.
Can you please provide a screen recording, screenshot or Sketch file for me to be able to see what you're talking about.

Cheers

**Comment by DWilliames** [comment]
I just pushed a release (v1.0.4) that should now fix this. 👍 

I will close this issue for now, assuming that the fix is stable — if you find that it hasn't been fixed, then please re-open this issue.

Cheers!
