### ISSUE TITLE
padding symbol support

### ISSUE THREAD

**Issue by redhajr** [DWilliames/paddy-sketch-plugin#31]
actually it doesn't support at all. it takes so much time when inputing padding while symbol is implemented anywhere.

**Comment by DWilliames** [comment]
Once again @redhajr. Can you please provide a bit more context for me to work with.

Can you please include a screenshot, screen recording or Sketch file.

**Comment by DWilliames** [comment]
@redhajr Any update on this? Unfortunately your explanation is very vague. Is this related to #36?

**Comment by DWilliames** [comment]
I just pushed a release (v1.0.4) that should now fix this. 👍 

I will close this issue for now, assuming that the fix is stable — if you find that it hasn't been fixed, then please re-open this issue.

Cheers!
