### ISSUE TITLE
[Bug] Not auto-updating when using symbols

### ISSUE THREAD

**Issue by mgerhard** [DWilliames/paddy-sketch-plugin#33]
same issues as documented here -> https://drive.google.com/file/d/12FF2igRmbjAhoikt-LnYeDcsQrCKGx63/view

(Sketch Version 48.2)

**Comment by DWilliames** [comment]
Thanks @mgerhard. 

I can't seem to replicate this issue. Have you tried restarting Sketch?

**Comment by mgerhard** [comment]
@DWilliames  i've even restarted the system, disabled all other plugins ... no change, still the same issue on symbols. BTW - setting up/changing the [x (v/h)(alignment)] values does not work either. only the initial setup works with the grouped background + text pressing ctrl+alt+p, defining the padding and changing the text / autoresizing afterwards.

**Comment by mgerhard** [comment]
@DWilliames when using spacing and distribution the initial setup e.g. 20v r works well - but chaning the Groupname to e.g. 30v l has no impact.

**Comment by kirloi** [comment]
Same here... padding or spacing doesn't automate anymore, only on prompt paddy dialog (on symbols the technic doesn't work off course). Did the same as the other users...

**Comment by Arroyodorado** [comment]
Same here. Doing everything as shown in the tutorials but only the initial setting of padding or spacing works, no auto-update. 
Set the debug variable in the plugin to true to see if anything useful is output in console but nothing is logged there for Sketch. Except for "Unix exception error: 17" which probably is totally unrelated.

macOS 10.12.6, Sketch 48.2

**Comment by rdoyle720** [comment]
Same issue here. Using sample file from tutorial, no response on symbols

**Comment by ollieevill** [comment]
Same issue with me.

**Comment by trvsss** [comment]
I have this issue, but it happens in and out of symbols if that helps.

**Comment by matt-bailey** [comment]
I think I'm also having the same issue.

If I just use a shape the padding is automatically added. However, if I convert that shape to a symbol the padding is no longer automatically applied, it just stops working...

**Comment by ollieevill** [comment]
@DWilliames Any update? Let us know if we can help replicate the bug. 

Thanks,
Ollie

**Comment by DWilliames** [comment]
Hey all! Sorry for the delay. I've been pretty busy recently, and hadn't had a chance to look at this.

I've started work on the next release – I've changed a couple of things, and think I might have fixed it.

Have a sneak peak if you can: https://github.com/DWilliames/paddy-sketch-plugin/archive/v1.0.4.zip and let me know if that works for you all! 👍 

Cheers

**Comment by Arroyodorado** [comment]
Hi David, cool, it works for me now with version 1.0.4. 
Thanks for the update and have a nice weekend,
8-)

**Comment by DWilliames** [comment]
I just pushed a release (v1.0.4) that should now fix this. 👍 

I will close this issue for now, assuming that the fix is stable — if you find that it hasn't been fixed, then please re-open this issue.

Cheers!
