### ISSUE TITLE
Modal window "Please select at least one layer to duplicate" keep poping.

### ISSUE THREAD

**Issue by hdche** [DWilliames/paddy-sketch-plugin#34]
![screen shot 2018-02-19 at 13 31 16](https://user-images.githubusercontent.com/22611248/36379572-674c32f0-157f-11e8-8320-b4f382d50f05.png)

version 1.0.3.

**Comment by panchovm** [comment]
I have the same issue. It's impossible to close the app. Thank you for reporting

**Comment by brandensilva** [comment]
Unfortunately I've had to disable the plugin until this gets fixed because it continues to interrupt the workflow.

**Comment by Croops** [comment]
Yup I get the same error. Only started happening once I installed the Paddy plug in.

**Comment by PatrykLes** [comment]
Same here. Please help!

**Comment by sherifsaleh** [comment]
same problem, it just went away when i disabled the plugin.
https://sketchtalk.io/discussion/3044/error-message-please-select-at-least-one-layer-to-duplicate

**Comment by deezinerUK** [comment]
Yep - same here. Disabled plugin for now.

**Comment by mathieudutour** [comment]
duplicate of https://github.com/DWilliames/paddy-sketch-plugin/issues/18

**Comment by DWilliames** [comment]
Thanks all for highlighting this — I'm gonna mark this as a duplicate of https://github.com/DWilliames/paddy-sketch-plugin/issues/18; and move all further conversations in there. Thanks for your patience as I try and figure out why Craft is causing this conflict.
