### ISSUE TITLE
[Bug] Automatic padding/alignment doesn't work.

### ISSUE THREAD

**Issue by Dorphe** [DWilliames/paddy-sketch-plugin#35]
Basically what the title says. Automatic padding with a shape doesn't work, automatic alignment and spacing either. Only thing that works is with a shape and text layer (a button, for instance). I've attached a sketch file and a video.

Thanks!

[paddy-bugs.zip](https://github.com/DWilliames/paddy-sketch-plugin/files/1737550/paddy-bugs.zip)

**Comment by listao** [comment]
I've noticed this as well. It was working for me in the past few day, but seems to have stopped working. Even when going by what the docs are showing.

**Comment by JesseBilsten** [comment]
Yup, the automatic alignment is broken for me too.

**Comment by ziyafenn** [comment]
Yep, same here. Happened after the last update.

**Comment by juliabaulin** [comment]
The same here!

**Comment by DWilliames** [comment]
Thanks all for letting me know!

I suspect this may be due to something I implemented to stop Paddy from trying to update every time – however, it appears to be too aggressive.

I think I may have a fix in the upcoming release... hang tight!

**Comment by DWilliames** [comment]
Can you all check this sneak peak of the next release, and let me know if it works for you now: https://github.com/DWilliames/paddy-sketch-plugin/archive/v1.0.4.zip

It seems to be working for me :P

**Comment by DWilliames** [comment]
I just pushed a release (v1.0.4) that should now fix this. 👍 

I will close this issue for now, assuming that the fix is stable — if you find that it hasn't been fixed, then please re-open this issue.

Cheers!
