### ISSUE TITLE
[Enhancement] Center align layers with "min width" padding

### ISSUE THREAD

**Issue by ekaterinasyuma** [DWilliames/paddy-sketch-plugin#37]
Hi! I have a huge library with buttons, and all of them have "min width" specifications. In this case, the paddings are 15; 24; 17; 24 and width >=100. When I use a short title for my button, such as "Add", the plugin automatically fits the width to 100 px (it's super cool!), but the text field doesn't seem to be aligned to the centre. 
![alignment](https://user-images.githubusercontent.com/36654817/36408376-c94d77e6-1626-11e8-968b-f94c5b7ec10a.gif)

**Comment by DWilliames** [comment]
Hey @ekaterinasyuma. Thanks for getting in touch!
Yeah; it was never the initial behaviour for the text to auto-centre with 'min-width' — however, I feel in most cases this is what is expected. So I'll try and make it the default behaviour.

Thanks for pointing it out. 👍

**Comment by DWilliames** [comment]
@ekaterinasyuma I've made the fix. Although, it doesn't work perfectly with Symbols at the moment :P

**Comment by DWilliames** [comment]
I just pushed a release (v1.0.4) that should now fix this. 👍 

I will close this issue for now, assuming that the fix is stable — if you find that it hasn't been fixed, then please re-open this issue.

Cheers!

**Comment by jamesgrubb** [comment]
Hi, Im using an icon with my button. Using w>=160 creates some quirky behaviour. Icon and text seem to centre themselves?
