### ISSUE TITLE
[Enhancement] Can Shapes and Text Fields Stay on Whole Pixels on Resize?

### ISSUE THREAD

**Issue by trvsss** [DWilliames/paddy-sketch-plugin#38]
Because your padding recalculates everything, it's causing lines/strokes/shape edges to become blurry on resize. I believe this could be remedied by being super anal about maintaining everything on whole pixels, but this would be amazing. I'd just round to the nearest.

**Comment by DWilliames** [comment]
Ah cool. Yeah that's a really good point!

In some cases though – do you thing there would be people who would want the spacing etc. to be perfect, and not aligned to the pixels?

I was thinking; maybe I'll make sure it pixel-fits to whole number if the user has set 'Pixel fitting' on in Sketch preferences. Thoughts?

![screen shot 2018-02-25 at 2 14 34 am](https://user-images.githubusercontent.com/6570446/36631776-cd15e6ca-19d1-11e8-8162-d993a06021a7.png)

**Comment by trvsss** [comment]
I’m sure that would be handy for some people. My main concern is related to
UI design and things needing sharpness. That would work for me! If it’s
extra work to follow that setting or not I wonder if it would be worth it
cs just always remaining on whole pixels. It seems the major cases for use
are for UI as I mentioned.

**Comment by DWilliames** [comment]
@trvsss No worries. It's totally do-able.

Just to clarify; is this purely for the positioning of the layers (e.g. their 'x' and 'y')?
Or is it also for their size too? (width, height)

**Comment by DWilliames** [comment]
I just pushed a release (v1.0.4) that should now include this. 👍 

I will close this issue for now, assuming that the fix is stable — if you find that it hasn't been fixed, then please re-open this issue.

Cheers!

**Comment by trvsss** [comment]
This is working perfectly now! Thank you!
