### ISSUE TITLE
[Bug] Paddy doesn't work with symbol 

### ISSUE THREAD

**Issue by amitdud** [DWilliames/paddy-sketch-plugin#39]
When i create a symbol from the group the padding not working when i override the text

**Comment by surajnaikin123** [comment]
I too observed this, they way it started working with a symbol is something like this. I created a symbol,  let's say with your initial text 'Normal Button' - first override it with a smaller text say 'Button' in an instance, it works. Then again override it with bigger text 'A Bigger Button', it starts to work.

**Comment by cjcheshire** [comment]
I thought I had this issue.  But I hadn't updated the resizing rules for the text layer so it looked like this:

![image](https://user-images.githubusercontent.com/437963/36537983-b820710e-17c9-11e8-87a8-c0ca18ac40a0.png)

---

**Ensure it is like this:**

![image](https://user-images.githubusercontent.com/437963/36537966-ad47d1aa-17c9-11e8-96b5-49b2ff93a6ce.png)

**Comment by dannylodesigns** [comment]
+1 having same issue.

**Comment by blaskotron** [comment]
Same, not working consistently.

**Comment by DWilliames** [comment]
Hey all – are you able to provide a bit more details if possible for what exactly is not working.
Is it just that it is not resizing automatically consistently? 
Or is it that it is resizing to the wrong size? If so, please provide a screenshot or screen recording to help.

Cheers.

**Comment by blaskotron** [comment]
Symbol instance size when text is overridden. Sometimes it will randomly. I've used a demo file that came from another post. But also created by own here in the zip. 

Sketch version 48.2

<img width="597" alt="screen shot 2018-02-24 at 12 16 31 pm" src="https://user-images.githubusercontent.com/2779211/36633066-d278df8e-195c-11e8-8453-d796993e4940.png">

[Paddy Issue.sketch.zip](https://github.com/DWilliames/paddy-sketch-plugin/files/1754693/Paddy.Issue.sketch.zip)

**Comment by DWilliames** [comment]
I just pushed a release (v1.0.4) that should now fix this. 👍 

I will close this issue for now, assuming that the fix is stable — if you find that it hasn't been fixed, then please re-open this issue.

Cheers!

**Comment by Weissenberger13** [comment]
Hey, ive been having this issue as well. It was working perfectly and has now stopped altogether whenever I override the text. 

Any ideas?

Thanks

**Comment by mooona** [comment]
still not working, with symbols: when I create symbol and try to hide stuff from it or make text bigger it's not working, however, it works fine inside the symbol page but when I try to use it as dynamic symbol it doesn't work :(
