### ISSUE TITLE
Wonder if it's possible to 'force' same widths? 

### ISSUE THREAD

**Issue by Chrisedmo** [DWilliames/paddy-sketch-plugin#4]
Firstly, I love this plugin! Im just having a ply and trying to set up a master wireframe document. However I've run into a problem… In the image below, when I resize it or change the text, sometimes the image background on the top will be smaller or bigger than the text box below? 

Any ideas how I can get around this? 

![screen shot 2018-02-06 at 10 44 23](https://user-images.githubusercontent.com/255639/35855381-f4ea8f4e-0b2a-11e8-9446-4275149043fc.png)

And here is how I have it all set up… 

![screen shot 2018-02-06 at 10 46 47](https://user-images.githubusercontent.com/255639/35855409-0f4c16d2-0b2b-11e8-9db2-9abb79613f71.png)

**Comment by DWilliames** [comment]
Hmm. 

1. Make sure your text labels have a 'fixed' width to them

2. Try setting a set size of 'Rectangle 2'. By changing the name to something like `Rectangle 2 [40 20 80;w=250]`. That should make sure the rectangle always stays at a size of 250.

Let me know how you go 👍

**Comment by DWilliames** [comment]
Hey @Chrisedmo; this may have been an issue that existed with fixed-widths. I just pushed an update, version 1.0.2 that should fix this. Can you verify if it does indeed fix it for you?

I will close this issue in the meantime. If the problem does still persist, then please re-open this.
