### ISSUE TITLE
[Bug] Automatic applying not working

### ISSUE THREAD

**Issue by sonjaporter** [DWilliames/paddy-sketch-plugin#41]
Sketch: 48.2
Paddy: 1.0.3

Padding/spacing not automatically applying when clicking outside group. See attached video.

[Paddy bug_small.zip](https://github.com/DWilliames/paddy-sketch-plugin/files/1747863/Paddy.bug_small.zip)

**Comment by dannylodesigns** [comment]
+1 same issue. Only applies padding (to non symbols only, symbols just aren't working right now for me) if I force it through the plugins dropdown. When i click "Enter padding for selection" The dialog comes up with the numbers applied to the layer already filled in.

**Comment by calderaricaio** [comment]
Same here! Sketch 48.2 (47327) Paddy V1.0.3

**Comment by evb-sun** [comment]
Same here, Sketch 48.2 (47327) Paddy V1.0.3

**Comment by DWilliames** [comment]
Thanks all! Thanks for the video @sonjaporter – it really helps 👍 

This is weird that it's not working for you. It is working fine for me... 🤔 
I have changed the approach a little for how Paddy decides when to update in the next release... hopefully that will fix it for everyone.

**Comment by DWilliames** [comment]
I just pushed a release (v1.0.4) that should now fix this. 👍 

I will close this issue for now, assuming that the fix is stable — if you find that it hasn't been fixed, then please re-open this issue.

Cheers!

**Comment by juliabaulin** [comment]
Thanks for fixing @DWilliames The new update resolved this problem for me!

**Comment by bhosler** [comment]
I am still having problems with auto-updating the sizing.  Symbols all the time and non-symbols when I change the padding numbers on the layer.

**Comment by bhosler** [comment]
It appears to not be working when there are nested symbols.
