### ISSUE TITLE
[Bug] Padding set to zero when using invalid value

### ISSUE THREAD

**Issue by wouterramaker** [DWilliames/paddy-sketch-plugin#42]
Currently when the value for the padding is invalid (for example `[A10]`), the plugin sets it to `0` and grows the element to it's parents size. 

The preferred action would be to ignore it.

**Comment by DWilliames** [comment]
I just pushed a release (v1.0.4) that should now fix this. 👍 

I will close this issue for now, assuming that the fix is stable — if you find that it hasn't been fixed, then please re-open this issue.

Cheers!
