### ISSUE TITLE
[BUG] Can't select Paddy layer group

### ISSUE THREAD

**Issue by ziyafenn** [DWilliames/paddy-sketch-plugin#44]
#### Actual behavior:

When i try to select the Paddy layer group from the artboard (not from layer list) it selects it for a one second and then deselects it. 

Problem occurs when Paddy group is nested inside another group.

![screenflow](https://user-images.githubusercontent.com/314302/36666730-cef8bbfa-1aeb-11e8-9b78-8bd070cab462.gif)

Paddy version: 1.0.4
Sketch version: 48.2

**Comment by Arkkimaagi** [comment]
I came here to report a possibly related issue.

I have three symbols in a group with `Tabgroup [0h t]`-name in it. The Tabgroup is nested within another group itself.

**Comment by dorian-grey** [comment]
Same here, but also happens when directly select a layer on the Artboard: Always need to select it twice, because it gets deselected 0,5 seconds after the first time.

**Comment by DWilliames** [comment]
Hey all – did the latest update (v1.0.5) fix this?

**Comment by ziyafenn** [comment]
Seem to be fixed

**Comment by DWilliames** [comment]
Awesome. Thanks @ziyafenn
