### ISSUE TITLE
Paddy interferes with ENTER shortcut to open groups

### ISSUE THREAD

**Issue by dorian-grey** [DWilliames/paddy-sketch-plugin#46]
#### Expected behavior:

Selecting a layer group and then hitting Enter opens the layer group in the layer panel.

#### Actual behavior:
Selecting a layer group that includes a layer with padding added and hitting Enter doesn't open the group.

#### Steps to reproduce:
1. Add information for Paddy to a layer name
2. Group it
3. Select the group
4. Hit Enter

**Comment by listao** [comment]
I am seeing the same bug as well. This doesn't seem to be limited to the hitting "Enter" to open the layer group, but also affects clicking into a layer group as well. Clicking into a layer group, it will allow you to, but then as after a ~1 sec, you lose focus on the element and the layer group is closed forcing you to do it all over again. Leaving you with no ability to actually make the edit you need to. 

Steps to reproduce are similar to OP, but instead, click on into the layer instead. 

Version 1.0.4.

**Comment by ajilderda** [comment]
I’m also experiencing issues with the new selection being lost. This mainly happens when using the escape key for selecting the parent group. It seems I found a fix. Will add a PR in a minute!

**Comment by DWilliames** [comment]
Hey all – I think I fixed this in v1.0.5. Can you please verify if it is working for you now.

**Comment by listao** [comment]
@DWilliames It looks resolved to me. Thanks!

**Comment by DWilliames** [comment]
Awesome. Thanks @listao
