### ISSUE TITLE
[Bug] 'Undo' not working correctly

### ISSUE THREAD

**Issue by nakele** [DWilliames/paddy-sketch-plugin#47]
#### Actual behavior: Once a box is moved and deselected few times to go back (cmd-z) takes many times, way more than the steps I've previously taken. This also affects cmd-shift-z to move forward in history.
(Please include a screenshot or screen recording if possible)
Unzip, it's a video
[paddy bug.zip](https://github.com/DWilliames/paddy-sketch-plugin/files/1763435/paddy.bug.zip)

#### Steps to reproduce: Move a box > deselect > wait few seconds > tap cmd-z > nothing happens
(Please attach a Sketch file if possible)
It will happen on a fresh file of sketch 48.2

**Comment by rorysmyth** [comment]
+1 on this. Especially on larger stacks. Looks like every move is saved as a step in the history

**Comment by scottwilliams58** [comment]
+1 from me too. It adds many *invisible* undo/history states and disables redo for me completely.

**Comment by chrismackintosh** [comment]
Same issue.

**Comment by Dooode** [comment]
Same here

**Comment by c5inco** [comment]
Yeah this is actually a big issue - almost a show stopper.

**Comment by ibanbe** [comment]
Same here. Yes, that's a huge problem guys.
![ezgif-4-42fb9e4989](https://user-images.githubusercontent.com/12713579/36778587-6e7b8860-1c6d-11e8-9ad0-86b9bbb4197f.gif)

**Comment by matsaukeo** [comment]
seeing the same issue

**Comment by chrisaalid** [comment]
Also seeing the same issue.

**Comment by bbsody** [comment]
Seeing the same issue.

**Comment by DWilliames** [comment]
Thanks everyone for this!! I will try and look into it ASAP — I know it's extremely frustrating and a really really bad bug 😢 😱 

I can replicate this pretty easily too. 
In the mean time; I've found **double-tapping 'Cmd + Z'** seems to work.

**Comment by djmtype** [comment]
@DWilliames 

> In the mean time; I've found double-tapping 'Cmd + Z' seems to work. 

No, pressing Cmd + Z twice consecutively does not Undo anything for me with Paddy enabled – at least in Sketch 49.

**Comment by scottwilliams58** [comment]
> No, pressing Cmd + Z twice consecutively does not Undo anything for me with Paddy enabled – at least in Sketch 49.

Same, and Redo is **completely unavailable** to me.

**Comment by nakele** [comment]
It's not a matter of double pressing cmd-z but pressing cmd-z fast enough, very quickly many times it will eventually go back in history

**Comment by DWilliames** [comment]
Alright all — I just release v1.0.5. Can you all please check if this has fixed it for you?

**Comment by ibanbe** [comment]
It's working here now, thanks!!

**Comment by rorysmyth** [comment]
@DWilliames Seems to work, but introduced another one:

If you create a set of layers and group them (cmd+g), then cmd+r will not work. you need to unfocus the selection and reselect

**Comment by nakele** [comment]
@DWilliames seems to be working for me as well. 

In relation to the cmd+r (rename) it seems that when Paddy plugin is enabled, grouping 2 elements and then hitting cmd+r won't do anything because both the group and 1 layer of the group are select. 

In comparison when the plugin is not enabled, grouping 2 elements and then renaming the group is allowed because only the group is selected.

Video attached.
[rename.mov.zip](https://github.com/DWilliames/paddy-sketch-plugin/files/1775865/rename.mov.zip)

**Comment by DWilliames** [comment]
Thanks all – I'll close this for now. 

Thanks @rorysmyth and @nakele — I've created a new bug for this #62

**Comment by Arkkimaagi** [comment]
@DWilliames how did you fix this? I'm facing similar problems with a new plugin I'm writing and I can not figure out how you bypassed the undo trap. When ever the selection changes, I update text with a plugin. This causes similar problems with my plugin that yours had here. What did you do to go around this problem?
