### ISSUE TITLE
[Bug] Option to turn off update warning

### ISSUE THREAD

**Issue by blaskotron** [DWilliames/paddy-sketch-plugin#49]
First, I'm not even using paddy on this symbol or even in this document which is weird. 

But I'd like to turn off this warning that occurs when you edit a symbol with 10 or more instances. 
![image](https://user-images.githubusercontent.com/2779211/36760101-98bfb3f2-1be7-11e8-8425-afb439f228ea.png)

Annoying if you're working on existing symbol and you have to click this every time even if you don't make changes. And there is no slow down for me even with 30 symbols

**Comment by barmallion** [comment]
Same problem. No symbols with padding and view this window again and agin.

**Comment by ibanbe** [comment]
Same here!

**Comment by sonjaporter** [comment]
Same. 

Maybe better as a more subtile message (like with abstract - a small box at the bottom of the window). Or wait until the user goes back to the page (out of the symbols page) to ask to update symbols.

**Comment by DWilliames** [comment]
Yeah! Thanks all. Just realised I screwed up my logic — at the moment this window appears every time, not just after updating padding. Oops 😱 

Will fix in the next release.

**Comment by blaskotron** [comment]
The warning still pops up even when you don't make any symbol changes in a document with paddy elements. But I'd like to turn it off completely even so. Right now I have to disable the plugin to use my document without the constant warning.

**Comment by Dorphe** [comment]
Still a problem in 1.0.6. Appears every time I click on a layer in a symbol.

**Comment by DWilliames** [comment]
:( I'm so sorry guys. I think I'll remove the alert entirely – that must be incredibly annoying to see.
