### ISSUE TITLE
Issue with Undo (Cmd + Z)

### ISSUE THREAD

**Issue by iamsankalp** [DWilliames/paddy-sketch-plugin#55]
#### Expected behavior:

1. Draw a rectangle
2. Click anywhere outside to unselect the layer.
3. Press Cmd + Z for undo.

4. The rectangle should have been removed as that was the last step.

#### Actual behavior:

The rectangle first gets selected, then on a subsequent press of Cmd + Z again, the rectangle is removed.

**Can someone else also verify?** I noticed this bug today - it was there before the Sketch v49 update also.

I can say that this happens only if I have Paddy plugin enabled. I have checked by removing all others.

Thanks,
Sankalp

**Comment by bbsody** [comment]
Yes, I'm having the same issue.

**Comment by DWilliames** [comment]
Yep. Thanks for this @iamsankalp . This is such a bad bug! I'll mark this as a duplicate for now.
See here: https://github.com/DWilliames/paddy-sketch-plugin/issues/47
