### ISSUE TITLE
[Bug] Altering unwantedly the position of elements within a Paddy group each time you deselect an item within the group 

### ISSUE THREAD

**Issue by jadsd** [DWilliames/paddy-sketch-plugin#57]
Hi,

First of all I love you plugin!
I would love to use it for a lot of components in my design-system.

At this moment I am developing allot of components. Previously I used the plugin from Anima for stacks and (group) layer-alignment. But it fall short on automatically resize itself so that it surrounds all other layers.

Paddy works very well for buttons. But as je mentioned in your Github page and Medium article it does not work well yet with nested symbols. You're working on that. Can't wait for deep nested symbol support 

In past few days I was playing around with Paddy. I wanted to create a responsive tabbar using paddy. Unfortunately, I did not succeed in creating it. 

**the challenge: creating a responsive tabbar**
I created two symbols each with grouped a text and padding applied to it. Each group is centred on the artboard of the symbol. It  In addition to this, the symbol has an orange bar and the other symbol has a transparent bar. The two bars are set to scale to the with the width of the symbol.

The problem. when I place these two symbols on an artboard and group them together and apply Paddies distribution (0 distance between the items) to it,
Paddy malfunctions. Each time I deselect an item within the group the text within the symbols moves 1 or two pixels to the right. The text is not centred within the symbol anymore.

Is this a bug? A I doing something wrong? Can this have something to do that I've upgraded to sketch version 49?

video example:
https://vimeo.com/258042383
password: sketch

Kind regards,

José Augusto

**Comment by dannylodesigns** [comment]
This is happening to me as well now.

**Comment by Raghavdesi9ns** [comment]
This happened to me as well

**Comment by DWilliames** [comment]
This should now be fixed v1.0.7 – if you find it still persists; then please re-open this issue.
