### ISSUE TITLE
Symbols in Symbols do not work (

### ISSUE THREAD

**Issue by sunnyexe** [DWilliames/paddy-sketch-plugin#6]
It would be great if i could put resizable button in another symbol and then change text in overrides.

```
symbol «molecule»    //atom do not resize 
   symbol «atom»        //resizable button, resizing work
     text
     symbol «bg» [10 10]
```

**Comment by luxlogica** [comment]
This seems to be a repeat of Issue #3.

**Comment by DWilliames** [comment]
I'm going to tie this as 'Nested symbols' #3. Which unfortunately isn't possibly right now :(
