### ISSUE TITLE
[Bug] Paddy issue after sketch 49 update 

### ISSUE THREAD

**Issue by chanakairugal** [DWilliames/paddy-sketch-plugin#63]
### Bug report

Hi I have an unusual issue with the plugin after sketch new 49 update
#### Expected behavior:
Expected behavior should be paddings needs to apply soon after change txt content. 

#### Actual behavior:
But after the update its wont work :|

**Comment by schroepa** [comment]
Same here - nothing happens after text change :(

**Comment by aminta** [comment]
If you restart Sketch it works, but I believe it's a bug..

**Comment by DWilliames** [comment]
Hey @chanakairugal. Are you able to confirm if it works now after restarting Sketch?

**Comment by chanakairugal** [comment]
Yep its work after restart Sketch mate

**Comment by chanakairugal** [comment]
Hi @DWilliames,

Did you fixed that :) awesome...
