### ISSUE TITLE
Auto select layer issue

### ISSUE THREAD

**Issue by tikshow** [DWilliames/paddy-sketch-plugin#69]
Please check the video, how can I disable this?

https://www.youtube.com/watch?v=qdecqk77aqE

**Comment by tikshow** [comment]
Also it auto selects all of the layers if you create a group, not just the group itself.

**Comment by DWilliames** [comment]
I think I just fixed it with v1.0.6 – can you please confirm if this fixes it for you.

**Comment by tikshow** [comment]
It seems alright at first glance I'll test it thoroughly tomorrow. Thank you!

**Comment by tikshow** [comment]
It works great! You can close this issue.

Thank you!

**Comment by DWilliames** [comment]
Awesome. Great to hear. Thanks @tikshow
