### ISSUE TITLE
Nested Symbols

### ISSUE THREAD

**Issue by cswenke** [DWilliames/paddy-sketch-plugin#74]
Any thoughts on when nested symbols will work?

Is there a work around?

**Comment by fancymans** [comment]
There's already an issue on nested symbols. https://github.com/DWilliames/paddy-sketch-plugin/issues/3

**Comment by DWilliames** [comment]
Thanks @fancymans – please refer to #3 for further discussion on Nested Symbols @cswenke! 👍
