### ISSUE TITLE
 [Bug] The content moves on the left hand side out of the artboard

### ISSUE THREAD

**Issue by JoeMandrill** [DWilliames/paddy-sketch-plugin#76]
#### Expected behavior:

The symbols should normally resize  

#### Actual behavior:
After updating, the content of the symbol moves on the left side out of the artboard.

Here is a quick screen recording :
https://www.dropbox.com/sh/abman9rn16h7r1f/AADCpx-NMhU0Xdp8UryoSBkza?dl=0

**Comment by DWilliames** [comment]
Thanks for the screen recording... it really helps!!

That seems like a really annoying bug :( Thanks for the heads up @JoeMandrill

**Comment by lipegon** [comment]
+1 on this.

![bug](https://user-images.githubusercontent.com/22617512/37399644-88ab57ae-2782-11e8-837a-a645f9178c4c.gif)

**Comment by imhalfpirate** [comment]
This blew up my whole sketch file with padded buttons. Anybody found a quick fix for this?

**Comment by joekingalot** [comment]
Yea, this one is a dealbreaker for sure right now. Happens on 48.2 for me too.

**Comment by brunogdesign** [comment]
+1

**Comment by DWilliames** [comment]
Dang. So sorry about this guys. Looking into it now...

**Comment by DWilliames** [comment]
This should now be fixed v1.0.7 – if you find it still persists; then please re-open this issue.

**Comment by joekingalot** [comment]
Works amazingly now. Much thanks for the great support.

**Comment by chsWeb** [comment]
I am still seeing behavior related to this bug.

**Here is a demo video:**
[https://vimeo.com/261501561/ea7bb979ba](https://vimeo.com/261501561/ea7bb979ba)

**Here is the demo file used in the video:**
[https://www.dropbox.com/s/u29k5dsquk2i6i8/uiLibrary_popups-demoBug.sketch?dl=0](https://www.dropbox.com/s/u29k5dsquk2i6i8/uiLibrary_popups-demoBug.sketch?dl=0)

**Problem:** When setting padding and a width on a background layer, the layer is shifting off of the artboard when an object (text or shape) is grouped with the background layer.
