### ISSUE TITLE
Calculating of sizes of masked layers

### ISSUE THREAD

**Issue by 3rdrail** [DWilliames/paddy-sketch-plugin#78]
Hi, 

if i mask an image to a shape, the sizes are being calculated based on the image - not the the size of the shape. Even if i group the masked items separately...

Is there a way of ignoring the size of masked images and take the size of the shape as the base for calculating the paddings?

Thanks

**Comment by DWilliames** [comment]
@3rdrail try add a '-' before the name of the image. 

Here's a quick example; Paddy will ignore any layers that have the prefix '-' when calculating sizes...
![image](https://user-images.githubusercontent.com/6570446/37562419-ac65fa8c-2abb-11e8-8a01-db373be6499d.png)

Here's how it looks.
![image](https://user-images.githubusercontent.com/6570446/37562420-afe01b70-2abb-11e8-8bbb-2cb6465b3b22.png)

Even though the image is much bigger...
![image](https://user-images.githubusercontent.com/6570446/37562424-c1fd154c-2abb-11e8-858a-27e77f6f8a77.png)

**Comment by DWilliames** [comment]
@3rdrail Let me know how you go. But in the mean time; I'll close this off as an issue, as I think this answers your question. 👍
