### ISSUE TITLE
Middle align keeps jumping

### ISSUE THREAD

**Issue by thelefty** [DWilliames/paddy-sketch-plugin#8]
When I have a group with middle applied and lose focus after moving it, it then jumps up. Really annoying and weird. Insanely awesome plugin btw.

![feb-07-2018 11-10-50](https://user-images.githubusercontent.com/6673900/35933392-c378ec08-0bf7-11e8-9b25-e72c722b2be8.gif)

**Comment by luxlogica** [comment]
What objects have you included in your group? How is your group structured? It seems to be trying to align the 3 layers with a background layer somewhere.

**Comment by thelefty** [comment]
This shows the layers. Every time I click on and off the group it will move up. Super weird.

![image](https://user-images.githubusercontent.com/6673900/35955170-ef6a982c-0c4a-11e8-9c0f-4e50c0f4daad.png)

**Comment by DWilliames** [comment]
Good find for this bug!

I think I've figured out what the issue is. I'll make it now so that every time the group is 're-spaced' or 're-aligned', the group should be pinned at the top-left. So it should end up with the same coordinates as it did to begin with.

**Comment by DWilliames** [comment]
This should now be fixed. Please verify in the latest version. 
If it's not fixed, then please re-open this issue 👍

**Comment by thelefty** [comment]
@DWilliames hey we are close. So now when I click on and off the group it still jumps about 1px up or down. I think the reason is that the elements are not using whole numbers for x and y. Each time I click on and off the elements are getting new numbers with decimals. I triple checked to see if it was just the elements starting off on decimals but it's not. Something in the logic is off. Thanks for being so prompt.

**Comment by thelefty** [comment]
Example of the small jump:
![feb-08-2018 09-53-32](https://user-images.githubusercontent.com/6673900/35986350-0a82ef86-0cb6-11e8-8dcb-83356f31b3ef.gif)
