### ISSUE TITLE
[BUG]Paddy doesn't ignore masked layers

### ISSUE THREAD

**Issue by equinusocio** [DWilliames/paddy-sketch-plugin#81]
### Bug report
Hi, i'm working with paddy and a symbol used as fill color. By this way i can just make one component and change it's fill. Unfortunately paddy apply paddings from the edges of fill layer. I think it should ignore any element inside the layer that have paddings defined ([..., ...])

#### Expected behavior:
Paddy should ignore masked elements inside the element with padding.

#### Actual behavior:
Paddy doesn't ignore masked elements. Example
![sample](https://user-images.githubusercontent.com/10454741/37399482-14a789d6-2782-11e8-9aa7-ebaeafc4b73b.gif)

There is a way to make this work?

#### Steps to reproduce:
Make a mask and put a layer with the same size of the background.

**Comment by Raghavdesi9ns** [comment]
turn the color layer +mask to a symbol and then add Paddy parameter.
I always keep the color symbols as small as possible like 1x1 then, you can stretch color symbol to any size you want later.

**Comment by equinusocio** [comment]
@Raghav789 By this way i will have two symbols overrides

**Comment by mikeozornin** [comment]
@equinusocio in the suggestion https://github.com/DWilliames/paddy-sketch-plugin/issues/70 I showed how to use Paddy with symbol as BG and mask. The same way you create a button, you can find sketch sources examples there.

I you case you need to set - in front of symbol name.

**Comment by equinusocio** [comment]
It doesn't work, even the sketch files in the linked issue. Paddy doesn't update layers (even after a restart)
